sudo: required

os:
  - linux
  - osx

language:
  - cpp

arch:
  #repos:
  packages:
    # pacman packages
    - meson
    - clang
    - ninja
    # aur packages
  script:
    # Disable sanitizer build pending fix in kernel 4.13:
    # https://github.com/google/sanitizers/issues/856 and
    # https://github.com/google/sanitizers/issues/837
    #- CC=clang CXX=clang++ meson build/sanitizer -Db_sanitize=address
    #- meson test -C build_sanitizer
    - CC=clang CXX=clang++ meson build/clang --buildtype=release
    - meson test -C build/clang
    - CC=gcc CXX=g++ meson build/gcc --buildtype=release
    - mesontest -C build/gcc

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ninja python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install meson; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then SDKROOT=$(xcodebuild -version -sdk macosx Path) mkdir build && meson build && mesontest -C build; fi

